CREATE TABLE IF NOT EXISTS tbl (Id INT PRIMARY KEY AUTO_INCREMENT, Item VARCHAR(50), TC VARCHAR(10));
INSERT INTO tbl (Item, TC) VALUES ('apple','c_01');
INSERT INTO tbl (Item, TC) VALUES ('banana','c_01');
INSERT INTO tbl (Item, TC) VALUES ('apples','c_02');
INSERT INTO tbl (Item, TC) VALUES ('bananas','c_02');
INSERT INTO tbl (Item, TC) VALUES ('100','c_03');
INSERT INTO tbl (Item, TC) VALUES ('10','c_03');
INSERT INTO tbl (Item, TC) VALUES ('66','c_04');
INSERT INTO tbl (Item, TC) VALUES ('166','c_04');
INSERT INTO tbl (Item, TC) VALUES ('202','c_04');
INSERT INTO tbl (Item, TC) VALUES ('14','c_04');
INSERT INTO tbl (Item, TC) VALUES ('35','c_05');
INSERT INTO tbl (Item, TC) VALUES ('45','c_05');
INSERT INTO tbl (Item, TC) VALUES ('61','c_05');
INSERT INTO tbl (Item, TC) VALUES ('59','c_05');
INSERT INTO tbl (Item, TC) VALUES ('73','c_05');
INSERT INTO tbl (Item, TC) VALUES ('2','c_06');
INSERT INTO tbl (Item, TC) VALUES ('4','c_06');
INSERT INTO tbl (Item, TC) VALUES ('6','c_06');
INSERT INTO tbl (Item, TC) VALUES ('8','c_06');
INSERT INTO tbl (Item, TC) VALUES ('10','c_06');
INSERT INTO tbl (Item, TC) VALUES ('12','c_06');
INSERT INTO tbl (Item, TC) VALUES ('23','c_07');
INSERT INTO tbl (Item, TC) VALUES ('15','c_07');
INSERT INTO tbl (Item, TC) VALUES ('97','c_07');
INSERT INTO tbl (Item, TC) VALUES ('45','c_07');
INSERT INTO tbl (Item, TC) VALUES ('365','c_07');
INSERT INTO tbl (Item, TC) VALUES ('1234','c_07');
INSERT INTO tbl (Item, TC) VALUES ('523665','c_07');
INSERT INTO tbl (Item, TC) VALUES ('45','c_07');
INSERT INTO tbl (Item, TC) VALUES ('2971','c_07');
INSERT INTO tbl (Item, TC) VALUES ('22145','c_07');
INSERT INTO tbl (Item, TC) VALUES ('Wednesday morning, John Smith was walking on the street.','c_08');
INSERT INTO tbl (Item, TC) VALUES ('Monday evening, Alex More was wolking on the street.','c_09');
INSERT INTO tbl (Item, TC) VALUES ('Spring','c_10');
INSERT INTO tbl (Item, TC) VALUES ('Summer','c_10');
INSERT INTO tbl (Item, TC) VALUES ('Fall','c_10');
INSERT INTO tbl (Item, TC) VALUES ('Winter','c_10');