CREATE TABLE IF NOT EXISTS tbl (Id INT PRIMARY KEY AUTO_INCREMENT, Item VARCHAR(50));
INSERT INTO tbl (Item) VALUES ('Spring');
INSERT INTO tbl (Item) VALUES ('Summer');
INSERT INTO tbl (Item) VALUES ('Fall');
INSERT INTO tbl (Item) VALUES ('Winter');