CREATE TABLE IF NOT EXISTS tbl (Id INT PRIMARY KEY AUTO_INCREMENT, Item VARCHAR(50));
INSERT INTO tbl (Item) VALUES ('2');
INSERT INTO tbl (Item) VALUES ('4');
INSERT INTO tbl (Item) VALUES ('6');
INSERT INTO tbl (Item) VALUES ('8');
INSERT INTO tbl (Item) VALUES ('10');
INSERT INTO tbl (Item) VALUES ('12');