CREATE TABLE IF NOT EXISTS tbl (Id INT PRIMARY KEY AUTO_INCREMENT, Item VARCHAR(50));
INSERT INTO tbl (Item) VALUES ('35');
INSERT INTO tbl (Item) VALUES ('45');
INSERT INTO tbl (Item) VALUES ('61');
INSERT INTO tbl (Item) VALUES ('59');
INSERT INTO tbl (Item) VALUES ('73');