CREATE TABLE IF NOT EXISTS tbl (Id INT PRIMARY KEY AUTO_INCREMENT, Item VARCHAR(50));
INSERT INTO tbl (Item) VALUES ('66');
INSERT INTO tbl (Item) VALUES ('166');
INSERT INTO tbl (Item) VALUES ('202');
INSERT INTO tbl (Item) VALUES ('14');